# Notebook for processing Evolving Hockey data

## Housekeeping

### Import dependencies

In [1]:
from pathlib import Path

import pandas as pd
import numpy as np

from chickenstats.chicken_nhl import scrape_schedule, scrape_standings

from chickenstats.chicken_nhl.scrape import (scrape_game_info,
                                                       scrape_html_rosters,
                                                       scrape_shifts,
                                                       scrape_api_events,
                                                       scrape_api_rosters,
                                                       scrape_changes,
                                                       scrape_html_events,
                                                       scrape_pbp,
                                                       prep_pbp,
                                                       scrape_rosters
                                                      )

from chickenstats.chicken_nhl.stats import (prep_box_score,
                                                      )


from chickenstats.evolving_hockey.base import (munge_pbp, munge_rosters, prep_pbp)#, prep_pbp)

from chickenstats.chicken_nhl.info import (team_codes, correct_names_dict, correct_api_names_dict)

import requests

from unidecode import unidecode

from bs4 import BeautifulSoup

import re

from tqdm.auto import tqdm

import pickle

import datetime

import time

import os
from os.path import isfile, join

In [2]:
pd.set_option('display.max_columns', None)

## reading data

### pbp

In [3]:
folder_stem = Path('./raw/evolving_hockey')

pbp_path = folder_stem / 'pbp_eh.csv'

pbp = pd.read_csv(pbp_path, low_memory = False)

### shifts

In [4]:
shifts_path = folder_stem / 'shifts_eh.csv'

shifts = pd.read_csv(shifts_path, low_memory = False)

## Munging

In [5]:
rosters = munge_rosters(shifts)

In [6]:
pbp = prep_pbp(pbp, rosters)

In [ ]:
def prep_box_score(pbp,
    level: str = "game",
    strengths: bool = True,
    score: bool = False,
    teammates: bool = False,
    forwards: bool = False,
    defense: bool = False,
    own_goalie: bool = False,
    opposition: bool = False,
    opp_forwards: bool = False,
    opp_defense: bool = False,
    opp_goalie: bool = False,):
    
    df = pbp.copy()
    
    
    
    return df

In [8]:
pbp

,season,game_id,game_date,session,event_idx,game_period,game_seconds,period_seconds,clock_time,event,description,event_detail,zone,event_team,opp_team,player_1,player_1_id,player_1_position,player_2,player_2_id,player_2_position,player_3,player_3_id,player_3_position,event_length,coords_x,coords_y,change_on_count,change_off_count,change_on_players,change_off_players,event_on_1,event_on_1_id,event_on_1_position,event_on_2,event_on_2_id,event_on_2_position,event_on_3,event_on_3_id,event_on_3_position,event_on_4,event_on_4_id,event_on_4_position,event_on_5,event_on_5_id,event_on_5_position,event_on_6,event_on_6_id,event_on_6_position,event_on_7,event_on_7_id,event_on_7_position,forwards,forwards_id,defense,defense_id,own_goalie,own_goalie_id,opp_on_1,opp_on_1_id,opp_on_1_position,opp_on_2,opp_on_2_id,opp_on_2_position,opp_on_3,opp_on_3_id,opp_on_3_position,opp_on_4,opp_on_4_id,opp_on_4_position,opp_on_5,opp_on_5_id,opp_on_5_position,opp_on_6,opp_on_6_id,opp_on_6_position,opp_on_7,opp_on_7_id,opp_on_7_position,opp_forwards,opp_forwards_id,opp_defense,opp_defense_id,opp_own_goalie,opp_goalie_id,home_goalie,away_goalie,opp_goalie,own_goalie,home_team,away_team,is_home,home_skaters,away_skaters,home_score,away_score,game_score_state,game_strength_state,home_zone,pbp_distance,event_distance,event_angle,home_zonestart,face_index,pen_index,shift_index,pred_goal,zone_start,strength_state,opp_strength_state,score_state,opp_score_state,block,change,corsi,fac,fenwick,give,goal,hit,miss,pen0,pen2,pen4,pen5,pen10,shot,stop,take,ozf,nzf,dzf,ozs,nzs,dzs,otf
0,20162017,2016030111,2017-04-12,P,1,1,0,0,20:00,PSTR,Period Start- Local time: 7:11 EDT,7:11 EDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,MTL,NYR,0,0,0,0,0,0v0,EvE,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0v0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20162017,2016030111,2017-04-12,P,2,1,0,0,20:00,CHANGE,NaN,NaN,NaN,NYR,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,6.0,0.0,"NYR5, NYR30, NYR10, NYR13, NYR40, NYR27",NaN,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,HENRIK.LUNDQVIST,EMPTY NET,HENRIK.LUNDQVIST,MTL,NYR,0,0,5,0,0,0v0,5v5,NaN,NaN,NaN,NaN,NaN,0,0,1,NaN,NEU,5v5,5v5,0v0,0v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,1.0,0.0,0.0
2,20162017,2016030111,2017-04-12,P,3,1,0,0,20:00,CHANGE,NaN,NaN,NaN,MTL,NYR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,6.0,0.0,"MTL65, MTL62, MTL31, MTL21, MTL26, MTL8",NaN,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,CAREY.PRICE,MTL,NYR,1,5,5,0,0,0v0,5v5,NaN,NaN,NaN,NaN,NaN,0,0,2,NaN,NEU,5v5,5v5,0v0,0v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,1.0,0.0,0.0
3,20162017,2016030111,2017-04-12,P,4,1,0,0,20:00,FAC,MTL won Neu. Zone - NYR #13 HAYES vs MTL #65 SHAW,NaN,NEU,MTL,NYR,ANDREW.SHAW,ANDREW.SHAW,C,KEVIN.HAYES,KEVIN.HAYES,R,NaN,NaN,NaN,11,0.0,0.0,NaN,NaN,NaN,NaN,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,CAREY.PRICE,MTL,NYR,1,5,5,0,0,0v0,5v5,Neu,NaN,89.00,0.00,2.0,1,0,2,NaN,NaN,5v5,5v5,0v0,0v0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
4,20162017,2016030111,2017-04-12,P,5,1,11,11,19:49,HIT,"NYR #5 GIRARDI HIT MTL #65 SHAW, Def. Zone",NaN,DEF,NYR,MTL,DAN.GIRARDI,DAN.GIRARDI,D,ANDREW.SHAW,ANDREW.SHAW,C,NaN,NaN,NaN,5,-96.0,33.0,NaN,NaN,NaN,NaN,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,CAREY.PRICE,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,MTL,NYR,0,5,5,0,0,0v0,5v5,Off,NaN,33.73,78.02,NaN,1,0,2,NaN,NaN,5v5,5v5,0v0,0v0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62986,20162017,2016030416,2017-06-11,P,632,3,3597,1197,0:03,MISS,"NSH #10 SISSONS, Slap, Wide of Net, Off. Zone,...",Slap,OFF,NSH,PIT,COLTON.SISSONS,COLTON.SISSONS,C,NaN,NaN,NaN,NaN,NaN,NaN,3,70.0,23.0,NaN,NaN,NaN,NaN,AUSTIN.WATSON,AUSTIN.WATSON,L,COLTON.SISSONS,COLTON.SISSONS,C,CRAIG.SMITH,CRAIG.SMITH,C,FILIP.FORSBERG,FILIP.FORSBERG,L,P.K.SUBBAN,NaN,NaN,ROMAN.JOSI,ROMAN.JOSI,D,NaN,NaN,NaN,NaN,"AUSTIN.WATSON, COLTON.SISSONS, CRAIG.SMITH, FI...",NaN,ROMAN.JOSI,NaN,,BRIAN.DUMOULIN,BRIAN.DUMOULIN,D,BRYAN.RUST,BRYAN.RUST,R,CARL.HAGELIN,CARL.HAGELIN,L,MATT.MURRAY,MATT.MURRAY,G,RON.HAINSEY,RON.HAINSEY,D,SIDNEY.CROSBY,SIDNEY.CROSBY,C,NaN,NaN,NaN,NaN,"BRYAN.RUST, CARL.HAGELIN, SIDNEY.CROSBY",NaN,"BRIAN.DUMOULIN, RON.HAINSEY",NaN,MATT.MURRAY,NaN,MATT.MURRAY,MATT.MURRAY,EMPTY NET,NSH,PIT,1,6,5,0,2,0v2,Ev5,Off,30.0,29.83,50.44,2.0,57,4,337,0.198896,NaN,Ev5,5vE,0v2,2v0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62987,20162017,2016030416,2017-06-11,P,633,3,3600,1200,0:00,CHANGE,NaN,NaN,NaN,PIT,NSH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,6.0,NaN,"PIT30, PIT8, PIT17, PIT87, PIT62, PIT65",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,AUSTIN.WATSON,AUSTIN.WATSON,L,COLTON.SISSONS,COLTON.SISSONS,C,CRAIG.SMITH,CRAIG.SMITH,C,FILIP.FORSBERG,FILIP.FORSBERG,L,P.K.SUBBAN,NaN,NaN,ROMAN.JOSI,ROMAN.JOSI,D,NaN,NaN,NaN,NaN,"AUSTIN.WATSON, COLTON.SISSONS, CRAIG.SMITH, FI...",NaN,ROMAN.JOSI,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,6,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,338,NaN,NaN,EvE,EvE,2v0,0v2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
62988,20162017,2016030416,2017-06-11,P,634,3,3600,1200,0:00,CHANGE,NaN,NaN,NaN,NSH,PIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,6.0,NaN,"NSH59, NSH9, NSH76, NSH51, NSH10, NSH15",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,1,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,EvE,EvE,0v2,2v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
62989,20162017,2016030416,2017-06-11,P,635,3,3600,1200,0:00,PEND,Period End- Local time: 9:59 CDT,9:59 CDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,NaN,NaN,0v2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62990,20162017,2016030416,2017-06-11,P,636,3,3600,1200,0:00,GEND,Game End- Local time: 10:00 CDT,10:00 CDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,NaN,NaN,0v2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pbp.loc[pd.isna(pbp.event_team)].event.value_counts()

AttributeError: 'DataFrame' object has no attribute 'event'

In [ ]:
new_cols = {'event_index': 'event_idx',
            'event_type': 'event',
            'event_description': 'description',
            'event_zone': 'zone',
            'event_player_1': 'player_1',
            'event_player_1_id': 'player_1_id',
            'event_player_1_pos': 'player_1_position',
            'event_player_2': 'player_2',
            'event_player_2_id': 'player_2_id',
            'event_player_2_pos': 'player_2_position',
            'event_player_3': 'player_3',
            'event_player_3_id': 'player_3_id',
            'event_player_3_pos': 'player_3_position',
            'num_on': 'change_on_count',
            'num_off': 'change_off_count', 
            'players_on': 'change_on_players',
            'players_off': 'change_off_players',
            'event_on_f': 'forwards',
            'event_on_f_id': 'forwards_id',
            'event_on_d': 'defense',
            'event_on_d_id': 'defense_id',
            'event_on_g': 'own_goalie',
            'event_on_g_id': 'own_goalie_id',
            'opp_on_f': 'opp_forwards',
            'opp_on_f_id': 'opp_forwards_id',
            'opp_on_d': 'opp_defense',
            'opp_on_d_id': 'opp_defense_id',
            'opp_on_g': 'opp_own_goalie',
            'opp_on_g_id': 'opp_goalie_id',}

In [9]:
pbp

,season,game_id,game_date,session,event_index,game_period,game_seconds,period_seconds,clock_time,event_type,event_description,event_detail,event_zone,event_team,opp_team,event_player_1,event_player_1_id,event_player_1_pos,event_player_2,event_player_2_id,event_player_2_pos,event_player_3,event_player_3_id,event_player_3_pos,event_length,coords_x,coords_y,num_on,num_off,players_on,players_off,event_on_1,event_on_1_id,event_on_1_pos,event_on_2,event_on_2_id,event_on_2_pos,event_on_3,event_on_3_id,event_on_3_pos,event_on_4,event_on_4_id,event_on_4_pos,event_on_5,event_on_5_id,event_on_5_pos,event_on_6,event_on_6_id,event_on_6_pos,event_on_7,event_on_7_id,event_on_7_pos,event_on_f,event_on_f_id,event_on_d,event_on_d_id,event_on_g,event_on_g_id,opp_on_1,opp_on_1_id,opp_on_1_pos,opp_on_2,opp_on_2_id,opp_on_2_pos,opp_on_3,opp_on_3_id,opp_on_3_pos,opp_on_4,opp_on_4_id,opp_on_4_pos,opp_on_5,opp_on_5_id,opp_on_5_pos,opp_on_6,opp_on_6_id,opp_on_6_pos,opp_on_7,opp_on_7_id,opp_on_7_pos,opp_on_f,opp_on_f_id,opp_on_d,opp_on_d_id,opp_on_g,opp_on_g_id,home_goalie,away_goalie,opp_goalie,own_goalie,home_team,away_team,is_home,home_skaters,away_skaters,home_score,away_score,game_score_state,game_strength_state,home_zone,pbp_distance,event_distance,event_angle,home_zonestart,face_index,pen_index,shift_index,pred_goal,zone_start,strength_state,opp_strength_state,score_state,opp_score_state,block,change,corsi,fac,fenwick,give,goal,hit,miss,pen0,pen2,pen4,pen5,pen10,shot,stop,take,ozf,nzf,dzf,ozs,nzs,dzs,otf
0,20162017,2016030111,2017-04-12,P,1,1,0,0,20:00,PSTR,Period Start- Local time: 7:11 EDT,7:11 EDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,MTL,NYR,0,0,0,0,0,0v0,EvE,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,0v0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20162017,2016030111,2017-04-12,P,2,1,0,0,20:00,CHANGE,NaN,NaN,NaN,NYR,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,6.0,0.0,"NYR5, NYR30, NYR10, NYR13, NYR40, NYR27",NaN,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,HENRIK.LUNDQVIST,EMPTY NET,HENRIK.LUNDQVIST,MTL,NYR,0,0,5,0,0,0v0,5v5,NaN,NaN,NaN,NaN,NaN,0,0,1,NaN,NEU,5v5,5v5,0v0,0v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,1.0,0.0,0.0
2,20162017,2016030111,2017-04-12,P,3,1,0,0,20:00,CHANGE,NaN,NaN,NaN,MTL,NYR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,6.0,0.0,"MTL65, MTL62, MTL31, MTL21, MTL26, MTL8",NaN,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,CAREY.PRICE,MTL,NYR,1,5,5,0,0,0v0,5v5,NaN,NaN,NaN,NaN,NaN,0,0,2,NaN,NEU,5v5,5v5,0v0,0v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,1.0,0.0,0.0
3,20162017,2016030111,2017-04-12,P,4,1,0,0,20:00,FAC,MTL won Neu. Zone - NYR #13 HAYES vs MTL #65 SHAW,NaN,NEU,MTL,NYR,ANDREW.SHAW,ANDREW.SHAW,C,KEVIN.HAYES,KEVIN.HAYES,R,NaN,NaN,NaN,11,0.0,0.0,NaN,NaN,NaN,NaN,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,CAREY.PRICE,MTL,NYR,1,5,5,0,0,0v0,5v5,Neu,NaN,89.00,0.00,2.0,1,0,2,NaN,NaN,5v5,5v5,0v0,0v0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
4,20162017,2016030111,2017-04-12,P,5,1,11,11,19:49,HIT,"NYR #5 GIRARDI HIT MTL #65 SHAW, Def. Zone",NaN,DEF,NYR,MTL,DAN.GIRARDI,DAN.GIRARDI,D,ANDREW.SHAW,ANDREW.SHAW,C,NaN,NaN,NaN,5,-96.0,33.0,NaN,NaN,NaN,NaN,DAN.GIRARDI,DAN.GIRARDI,D,HENRIK.LUNDQVIST,HENRIK.LUNDQVIST,G,J.T.MILLER,NaN,NaN,KEVIN.HAYES,KEVIN.HAYES,R,MICHAEL.GRABNER,MICHAEL.GRABNER,R,RYAN.MCDONAGH,RYAN.MCDONAGH,D,NaN,NaN,NaN,NaN,"KEVIN.HAYES, MICHAEL.GRABNER",NaN,"DAN.GIRARDI, RYAN.MCDONAGH",NaN,HENRIK.LUNDQVIST,ANDREW.SHAW,ANDREW.SHAW,C,ARTTURI.LEHKONEN,ARTTURI.LEHKONEN,L,CAREY.PRICE,CAREY.PRICE,G,DWIGHT.KING,DWIGHT.KING,L,JEFF.PETRY,JEFF.PETRY,D,JORDIE.BENN,JORDIE.BENN,D,NaN,NaN,NaN,NaN,"ANDREW.SHAW, ARTTURI.LEHKONEN, DWIGHT.KING",NaN,"JEFF.PETRY, JORDIE.BENN",NaN,CAREY.PRICE,CAREY.PRICE,HENRIK.LUNDQVIST,CAREY.PRICE,HENRIK.LUNDQVIST,MTL,NYR,0,5,5,0,0,0v0,5v5,Off,NaN,33.73,78.02,NaN,1,0,2,NaN,NaN,5v5,5v5,0v0,0v0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62986,20162017,2016030416,2017-06-11,P,632,3,3597,1197,0:03,MISS,"NSH #10 SISSONS, Slap, Wide of Net, Off. Zone,...",Slap,OFF,NSH,PIT,COLTON.SISSONS,COLTON.SISSONS,C,NaN,NaN,NaN,NaN,NaN,NaN,3,70.0,23.0,NaN,NaN,NaN,NaN,AUSTIN.WATSON,AUSTIN.WATSON,L,COLTON.SISSONS,COLTON.SISSONS,C,CRAIG.SMITH,CRAIG.SMITH,C,FILIP.FORSBERG,FILIP.FORSBERG,L,P.K.SUBBAN,NaN,NaN,ROMAN.JOSI,ROMAN.JOSI,D,NaN,NaN,NaN,NaN,"AUSTIN.WATSON, COLTON.SISSONS, CRAIG.SMITH, FI...",NaN,ROMAN.JOSI,NaN,,BRIAN.DUMOULIN,BRIAN.DUMOULIN,D,BRYAN.RUST,BRYAN.RUST,R,CARL.HAGELIN,CARL.HAGELIN,L,MATT.MURRAY,MATT.MURRAY,G,RON.HAINSEY,RON.HAINSEY,D,SIDNEY.CROSBY,SIDNEY.CROSBY,C,NaN,NaN,NaN,NaN,"BRYAN.RUST, CARL.HAGELIN, SIDNEY.CROSBY",NaN,"BRIAN.DUMOULIN, RON.HAINSEY",NaN,MATT.MURRAY,NaN,MATT.MURRAY,MATT.MURRAY,EMPTY NET,NSH,PIT,1,6,5,0,2,0v2,Ev5,Off,30.0,29.83,50.44,2.0,57,4,337,0.198896,NaN,Ev5,5vE,0v2,2v0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62987,20162017,2016030416,2017-06-11,P,633,3,3600,1200,0:00,CHANGE,NaN,NaN,NaN,PIT,NSH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,6.0,NaN,"PIT30, PIT8, PIT17, PIT87, PIT62, PIT65",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,AUSTIN.WATSON,AUSTIN.WATSON,L,COLTON.SISSONS,COLTON.SISSONS,C,CRAIG.SMITH,CRAIG.SMITH,C,FILIP.FORSBERG,FILIP.FORSBERG,L,P.K.SUBBAN,NaN,NaN,ROMAN.JOSI,ROMAN.JOSI,D,NaN,NaN,NaN,NaN,"AUSTIN.WATSON, COLTON.SISSONS, CRAIG.SMITH, FI...",NaN,ROMAN.JOSI,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,6,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,338,NaN,NaN,EvE,EvE,2v0,0v2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
62988,20162017,2016030416,2017-06-11,P,634,3,3600,1200,0:00,CHANGE,NaN,NaN,NaN,NSH,PIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,6.0,NaN,"NSH59, NSH9, NSH76, NSH51, NSH10, NSH15",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,1,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,EvE,EvE,0v2,2v0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
62989,20162017,2016030416,2017-06-11,P,635,3,3600,1200,0:00,PEND,Period End- Local time: 9:59 CDT,9:59 CDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,NaN,NaN,0v2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62990,20162017,2016030416,2017-06-11,P,636,3,3600,1200,0:00,GEND,Game End- Local time: 10:00 CDT,10:00 CDT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,,NaN,NaN,EMPTY NET,EMPTY NET,NSH,PIT,0,0,0,0,2,0v2,EvE,NaN,NaN,NaN,NaN,NaN,57,4,339,NaN,NaN,NaN,NaN,0v2,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pbp.event_on_3.str.replace('..', '.', regex = False)

0                NaN
1         J.T.MILLER
2        CAREY.PRICE
3        CAREY.PRICE
4         J.T.MILLER
            ...
62986    CRAIG.SMITH
62987            NaN
62988            NaN
62989            NaN
62990            NaN
Name: event_on_3, Length: 62991, dtype: object